# MONGO_URL = 'mongodb://mongo_user:mongo_secret@0.0.0.0:27017/'
MONGO_URL = 'mongodb://mongo_user:mongo_secret@192.168.99.100:27017/'
INSTANCE_NAME = 'devdb'
STICKYNOTE_COLLECTION_NAME = 'stickynotes'
POSTTYPE_COLLECTION_NAME = 'posttypes'
COLLECTIONS = [STICKYNOTE_COLLECTION_NAME, POSTTYPE_COLLECTION_NAME]
